env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-uses-react: 'off'
  react/react-in-jsx-scope: 'off'