# Generated by Django 4.1.2 on 2022-11-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="info_url",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="shelf_life_days",
            field=models.IntegerField(blank=True, default=365, null=True),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient_quantity",
            field=models.CharField(default="1", max_length=128),
        ),
        migrations.AlterField(
            model_name="recipenutritionforpersion",
            name="calories_kcal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipenutritionforpersion",
            name="carbs_gram",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipenutritionforpersion",
            name="fat_gram",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipenutritionforpersion",
            name="protein_gram",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="cook_minute",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="image_url",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="language",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="number_of_people",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="recipe_url",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="description",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="image_url",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="language",
            field=models.CharField(default="en", max_length=128),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag_url",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="useringredient",
            name="purchase_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
