# Generated by Django 4.1.2 on 2022-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_ingredients_info_url_alter_ingredients_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="language",
            field=models.CharField(default="en", max_length=128),
        ),
    ]
