# Generated by Django 4.1.2 on 2022-11-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_recipes_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="language",
        ),
    ]
