# Generated by Django 4.1.2 on 2022-11-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_recipes_language_alter_tags_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="language",
        ),
        migrations.RemoveField(
            model_name="tags",
            name="language",
        ),
    ]
