# Generated by Django 4.1.2 on 2022-11-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_recipes_language_tags_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories_kcal_per_person", models.FloatField(default=0)),
                ("fat_gram_per_person", models.FloatField(blank=True, null=True)),
                ("carbs_gram_per_person", models.FloatField(blank=True, null=True)),
                ("protein_gram_per_persn", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="recipes",
            name="title",
            field=models.CharField(default="unknown", max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name="RecipeNutritionForPersion",
        ),
        migrations.AddField(
            model_name="recipenutrition",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recipes"
            ),
        ),
    ]
