# Generated by Django 4.1.2 on 2022-11-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_recipenutrition_alter_recipes_title_alter_tags_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("recipe_url", models.CharField(blank=True, max_length=128, null=True)),
                ("image_url", models.CharField(blank=True, max_length=128, null=True)),
                ("cook_minute", models.FloatField(blank=True, null=True)),
                ("number_of_people", models.IntegerField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "english"),
                            ("sp", "spanish"),
                            ("ch", "chinese"),
                            ("gm", "german"),
                            ("jp", "japanese"),
                            ("kr", "korean"),
                            ("hb", "hebrew"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Ingredients",
            new_name="Ingredient",
        ),
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="recipenutrition",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="recipetag",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="recipeuserforfavority",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="recipeuserforhistory",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
            ),
        ),
        migrations.DeleteModel(
            name="Recipes",
        ),
    ]
