# Generated by Django 4.1.2 on 2022-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_recipe_rename_ingredients_ingredient_rename_tags_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipetag",
            old_name="Tag_id",
            new_name="tag_id",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="info_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="image_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
