# Generated by Django 4.1.2 on 2022-11-06 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_recipenutrition_recipe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="shelf_life_days",
            field=models.PositiveIntegerField(blank=True, default=365, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cook_minute",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="number_of_people",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipenutrition",
            name="calories_kcal_per_person",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="recipenutrition",
            name="carbs_gram_per_person",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="recipenutrition",
            name="fat_gram_per_person",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="recipenutrition",
            name="protein_gram_per_persn",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
