# Generated by Django 4.1.2 on 2022-11-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_ingredient_shelf_life_days_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="ingredient_id",
            new_name="ingredient",
        ),
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="recipenutrition",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="recipetag",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="recipetag",
            old_name="tag_id",
            new_name="tag",
        ),
        migrations.RenameField(
            model_name="recipeuserforfavority",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="recipeuserforfavority",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="recipeuserforhistory",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="recipeuserforhistory",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="useringredient",
            old_name="ingredient_id",
            new_name="ingredient",
        ),
        migrations.RenameField(
            model_name="useringredient",
            old_name="user_id",
            new_name="user",
        ),
    ]
