# Generated by Django 4.1.2 on 2022-11-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rename_ingredient_id_recipeingredient_ingredient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="number_of_people",
            new_name="num_servings",
        ),
        migrations.RenameField(
            model_name="recipenutrition",
            old_name="calories_kcal_per_person",
            new_name="calories_kcal_per_serving",
        ),
        migrations.RenameField(
            model_name="recipenutrition",
            old_name="carbs_gram_per_person",
            new_name="carbs_gram_per_serving",
        ),
        migrations.RenameField(
            model_name="recipenutrition",
            old_name="fat_gram_per_person",
            new_name="fat_gram_per_serving",
        ),
        migrations.RenameField(
            model_name="recipenutrition",
            old_name="protein_gram_per_persn",
            new_name="protein_gram_per_serving",
        ),
    ]
