# Generated by Django 4.1.2 on 2022-11-08 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_rename_number_of_people_recipe_num_servings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="owners",
            field=models.ManyToManyField(
                related_name="ingredients",
                through="api.UserIngredient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="api.RecipeIngredient",
                to="api.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="users_who_cooked",
            field=models.ManyToManyField(
                related_name="cooked_recipes",
                through="api.RecipeUserForHistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="users_who_liked",
            field=models.ManyToManyField(
                related_name="liked_recipes",
                through="api.RecipeUserForFavority",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="recipes",
            field=models.ManyToManyField(
                related_name="tags", through="api.RecipeTag", to="api.recipe"
            ),
        ),
    ]
