# Generated by Django 4.1.2 on 2022-11-08 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0016_ingredient_owners_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeUserForFavority",
            new_name="UserRecipeFavorite",
        ),
        migrations.RenameModel(
            old_name="RecipeUserForHistory",
            new_name="UserRecipeHistory",
        ),
    ]
