# Generated by Django 4.1.2 on 2022-11-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_recipeuserforfavority_userrecipefavorite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipenutrition",
            name="id",
        ),
        migrations.AlterField(
            model_name="recipenutrition",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="api.recipe",
            ),
        ),
    ]
