# Generated by Django 4.1.2 on 2022-11-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_recipenutrition_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipenutrition",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="nutrition",
                serialize=False,
                to="api.recipe",
            ),
        ),
    ]
