# Generated by Django 4.1.2 on 2022-11-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_recipenutrition_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                default="previously null name", max_length=128, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
