# Generated by Django 4.1.2 on 2022-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_recipeingredient_unique_recipe_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.CharField(default="default", max_length=128),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_name_category"
            ),
        ),
    ]
