# Generated by Django 4.1.2 on 2022-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_recipeingredient_unique_recipe_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="info_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
