# Generated by Django 4.1.2 on 2022-11-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_ingredient_info_url_alter_recipe_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tag_url",
            new_name="info_url",
        ),
    ]
