# Generated by Django 4.1.2 on 2022-11-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_tag_category_alter_tag_name_tag_unique_name_category"),
        ("api", "0023_rename_tag_url_tag_info_url"),
    ]

    operations = []
