# Generated by Django 4.1.2 on 2022-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_merge_20221114_2227"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="shelf_life_days",
            new_name="refrigerator_days",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="freezer_days",
            field=models.PositiveIntegerField(blank=True, default=365, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="pantry_days",
            field=models.PositiveIntegerField(blank=True, default=365, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="info_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
