# Generated by Django 4.1.2 on 2022-11-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_shelf_life_days_ingredient_refrigerator_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="num_ingredients",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of types of ingredients, for sanity check purpose",
                null=True,
            ),
        ),
    ]
