# Generated by Django 4.1.2 on 2022-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_recipe_num_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="freezer_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="pantry_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="refrigerator_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
