# Generated by Django 4.1.2 on 2022-11-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_recipe_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("title", "recipe_url"), name="unique_recipe_title_url"
            ),
        ),
    ]
