# Generated by Django 4.1.2 on 2022-11-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_recipe_title_recipe_unique_recipe_title_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredient_quantity",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="category",
            field=models.CharField(default="foods", max_length=128),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="quantity_scale",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="quantity_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
