# Generated by Django 4.1.2 on 2022-11-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_rename_purchase_date_useringredient_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity_value",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
