# Generated by Django 4.1.2 on 2022-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_recipeingredient_quantity_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="info_url",
            field=models.URLField(blank=True, default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_url",
            field=models.URLField(blank=True, default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity_scale",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.CharField(blank=True, default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="info_url",
            field=models.URLField(blank=True, default="", max_length=2048),
            preserve_default=False,
        ),
    ]
