# Generated by Django 4.1.2 on 2022-11-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_ingredient_image_url_alter_ingredient_info_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "english"),
                    ("es", "spanish"),
                    ("zh", "chinese"),
                    ("de", "german"),
                    ("ja", "japanese"),
                    ("ko", "korean"),
                    ("he", "hebrew"),
                ],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "english"),
                    ("es", "spanish"),
                    ("zh", "chinese"),
                    ("de", "german"),
                    ("ja", "japanese"),
                    ("ko", "korean"),
                    ("he", "hebrew"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
