# Generated by Django 4.1.2 on 2022-11-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_recipe_language_alter_tag_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                blank=True, default="foods", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="info_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
