# Generated by Django 4.1.2 on 2022-11-25 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_recipe_language_alter_tag_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="useringredient",
            name="happiness",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
