# Generated by Django 4.1.2 on 2022-11-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_ingredient_category_alter_ingredient_image_url_and_more"),
        ("api", "0035_useringredient_happiness"),
    ]

    operations = []
