# Generated by Django 4.1.2 on 2022-12-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_merge_20221127_1230"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuantityScaleUnits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=16, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="useringredient",
            name="quantity_value",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="useringredient",
            name="quantity_scale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.quantityscaleunits",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity_scale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.quantityscaleunits",
            ),
        ),
    ]
