# Generated by Django 4.1.2 on 2022-12-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_quantityscaleunits_useringredient_quantity_value_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuantityScaleUnits",
            new_name="QuantityScaleUnit",
        ),
    ]
