# Generated by Django 4.1.2 on 2022-12-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_rename_quantityscaleunits_quantityscaleunit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrecipehistory",
            old_name="cooked_date",
            new_name="access_date",
        ),
        migrations.AddField(
            model_name="userrecipehistory",
            name="cooked",
            field=models.BooleanField(default=False),
        ),
    ]
