# Generated by Django 4.1.2 on 2022-12-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_rename_cooked_date_userrecipehistory_access_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useringredient",
            name="storage",
            field=models.IntegerField(
                choices=[(0, "pantry"), (1, "refrigerator"), (2, "freezer")], default=1
            ),
        ),
    ]
