# Generated by Django 4.1.2 on 2022-12-10 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0040_useringredient_storage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="users_who_cooked",
        ),
        migrations.AddField(
            model_name="recipe",
            name="users_who_viewed",
            field=models.ManyToManyField(
                related_name="viewed_recipes",
                through="api.UserRecipeHistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
