FROM python:3.10-slim

ENV DJANGO_DEBUG_MODE=False
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app/django
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
# Timeout is set to 0 to disable the timeouts of the workers to allow Cloud Run to handle instance scaling.
CMD exec gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 refrigerator_catalogue.wsgi:application
