name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  LOCATION: asia-northeast1
  REPO_NAME: repo
  IMAGE_NAME: healthup-django
  CLOUD_RUN_NAME: cloudrun-django-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_HEALTHUP }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build the django image
        run: |
          docker build -t ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${{ github.sha }} -f docker/django/Dockerfile.prod django
          docker build -t ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest -f docker/django/Dockerfile.prod django

      - name: Run migaration
        run: |
          echo "${{ secrets.ENV_FILE_MIGRATE }}" > .env.migrate && \
          docker run --rm --env-file .env.migrate ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${{ github.sha }} python manage.py makemigrations --check --noinput && \
          docker run --rm --env-file .env.migrate ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${{ github.sha }} python manage.py migrate

      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker ${LOCATION}-docker.pkg.dev

      - name: Push the built image to Artifact Registry
        run: |
          docker push ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${{ github.sha }}
          docker push ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${CLOUD_RUN_NAME} \
            --project=${PROJECT_ID} \
            --image=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${{ github.sha }} \
            --region=${LOCATION} \
            --allow-unauthenticated
