name: Run Django's tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
jobs:
  run_django_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and start the Django container
        run: docker compose -f docker/docker-compose.yml up django --build -d

      - name: Run tests inside the Django container and fail if some do not pass
        run: docker compose -f docker/docker-compose.yml exec django python manage.py test --noinput

