name: Verify migrations match the source code
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
jobs:
  run_makemigrations_and_verify_nothing_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and start the Django container
        run: docker compose -f docker/docker-compose.yml up django --build -d

      - name: Run makemigrations inside the Django container and fail if model changes are missing migrations
        run: docker compose -f docker/docker-compose.yml exec django python manage.py makemigrations --check --noinput
